services: 
  db:
    image: mariadb:latest
    hostname: wp_database
    container_name: wp_database
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    hostname: php_my_admin
    container_name: php_my_admin
    volumes:
      - php_my_admin_data:/var/www/html
    ports:
      - 8078:80
    # restart: always
    environment:
      PMA_ARBITRARY: 1 # разрешение на подключения к любому серверу
      TZ: "Europe/Moscow"
      PMA_HOST: ${DB_HOST}

volumes:
  db_data: {}
  php_my_admin_data: {}
